name: 03 - Workflow Runners
on: push
jobs:
    ubuntu-echo:
          runs-on:  ubuntu-latest
          steps:
            - name: runs on ubutu
              run: echo "I am running this code in $RUNNER_OS"