name: 04 - Using Actions
on: 
    push
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: checkout code
           run: echo "Checkout code"
    
    printingFolder:
        runs-on: ubuntu-latest
        steps:
            - name: printing folders
              run: echo "Printing Folders"