name: 10 - Controlling the Execution Flow
on:
  workflow_dispatch:
    inputs:
        pass-unit-test:
            type: boolean
            description: whether unit test will pass or not
            default: true
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "Running tests"
    unit-test:
        runs-on: ubuntu-latest          
    deploy-nonprod:
        runs-on: ubuntu-latest 
    e2e-Tests:
        runs-on: ubuntu-latest
    deploy-prod:
        runs-on: ubuntu-latest 
