name: 15-working with matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 21.x]
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experimental

    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJs ${{ matrix.node-version }}"
      - name: upload test results
        run: echo "uploading test results"

  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, big]
        include:
        - color: red
          opacity: 75
        - shape: circle
          opacity: 100
        - color: red
          shape: triangle
        - opacity: 50
        - color: green
          shape: circle
          size: medium
        exclude:
        - color: green
          shape: circle
    steps:
    - run: echo "Color=${{ matrix.color }}, Shape=${{ matrix.shape }}, Size=${{ matrix.size }}"

