name: 15-working with matrices

on: 
    workflow_dispatch:
jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            node-version: [ 18.x , 20.x , 21.x]
            os:
                - ubuntu-latest
                - windos-latest
            include:
                    - os: ubuntu-latest
                      node-verison: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental 
        steps:
        - name: setup node 
          uses: actions/setup-node@v4
          with: 
           node-verson: ${{ matrix.node-version }}
        - name: Fail if experimental
          if: matrix.tag == 'experimental'
          run: exit 1
        - name: Perform some tests
          run: |
            echo "Running tests on OS ${{ matrix.os }} and NodeJs ${{ matrix.node-version }}"
            sleep 10
        - name: upload test results
          run: echo "uploading test  results"
