name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
            - "https://www.google.com"
            - "httsss://www.orangle.com"
            - "https://www.EshaanTheGreat.com"
       
      max_trials:
        description: Maximum number of trials until action fails.
        default: '10'
        required: false
      delay:
       description: Delay in seconds between trials.
       default: '5'
       required: false  

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trails: ${{inputs.max_trials}}
          delay: ${{inputs.delay}}
         

